export default function Favicons() {
  return (
    <>
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicons/16x16.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicons/32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="96x96"
        href="/favicons/96x96.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="128x128"
        href="/favicons/128x128.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="196x196"
        href="/favicons/196x196.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="228x228"
        href="/favicons/228x228.png"
      />
      <link
        rel="apple-touch-icon-precomposed"
        sizes="152x152"
        href="/favicons/152x152.png"
      />
      <link
        rel="apple-touch-icon-precomposed"
        sizes="167x167"
        href="/favicons/167x167.png"
      />
      <link
        rel="apple-touch-icon-precomposed"
        sizes="180x180"
        href="/favicons/180x180.png"
      />
    </>
  )
}
